name: Proper CI 

on: 
  push: 

jobs: 
  test: 
    name: Run test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo 
        uses: actions/checkout@v4 

      - name: setup node.js & npm 
        uses: actions/setup-node@v4

      - run: npm install 


      - run: npm test 
      - run: npm typecheck 
      
  lint: 
      name: run linter 
      runs-on: ubuntu-latest 
      steps: 
        - uses: actions/checkout@v4 
        - uses: actions/setup-node@v4
        - run: npm install 
        - run: npm run eslint 


      
     
